image:
    name: ubuntu:18.04

variables:
    GIT_STRATEGY: clone

before_script:
  - apt-get update -qq
  - apt-get install -y wget git build-essential
  - wget https://github.com/bazelbuild/bazel/releases/download/1.1.0/bazel_1.1.0-linux-x86_64.deb
  - apt install -y ./bazel_1.1.0-linux-x86_64.deb
  - git clone https://github.com/google/verible.git verible
  - cd verible && bazel build --noshow_progress --cxxopt='-std=c++17' //...
  - cd -

build:
    script:
        - printf "%s\n%s\n\n" "Verible commit:" "$(git --git-dir=verible/.git log -1 --pretty=oneline)"
        - ./test_loop.sh
    when: manual
